title = "Gitleaks Config"

[[allowlists]]
description = "Ignore known false positives and non-sensitive files"
paths = [
    "agentic-spring-ai-studio/agentic-spring-ai-studio-server/docker/middleware/docker-compose.yaml",
    "agentic-spring-ai-studio/agentic-spring-ai-studio-server/agentic-spring-ai-studio-server-admin/src/main/resources/static/3088.async.js",
    "agentic-spring-ai-studio/agentic-spring-ai-studio-server/agentic-spring-ai-studio-server-admin/src/main/resources/static/p__Setting__ModelService__index.async.js",
    "agentic-spring-ai-studio/agentic-spring-ai-studio-server/agentic-spring-ai-studio-server-core/src/main/java/io/github/agentic/spring/ai/studio/core/utils/security/RSACryptUtils.java",
    "agentic-spring-ai-studio/agentic-spring-ai-studio-server/agentic-spring-ai-studio-server-admin/src/main/resources/static/2782.async.js",
    "agentic-spring-ai-studio/agentic-spring-ai-studio-server/agentic-spring-ai-studio-server-core/src/main/resources/keys/private.pem",
    "agentic-spring-ai-studio/agentic-spring-ai-studio-server/agentic-spring-ai-studio-server-admin/src/main/resources/static/p__App__Workflow__index.async.js",
    "agentic-spring-ai-studio/agentic-spring-ai-studio-server/agentic-spring-ai-studio-server-admin/src/main/resources/static/6651.async.js"
]
