<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.github.agentic-spring-ai</groupId>
        <artifactId>agentic-spring-ai-admin</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>agentic-spring-ai-admin-server-openapi</artifactId>
    <name>Agentic Spring AI Admin Server OpenAPI</name>
    <description>OpenAPI of admin server.</description>
    <url>https://github.com/alibaba/agentic-spring-ai</url>
    <scm>
        <connection>git://github.com/alibaba/agentic-spring-ai.git</connection>
        <developerConnection>git@github.com:alibaba/agentic-spring-ai.git</developerConnection>
        <url>https://github.com/alibaba/agentic-spring-ai</url>
    </scm>

    <properties>
        <central.publishing.skip>true</central.publishing.skip>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>io.github.agentic-spring-ai</groupId>
            <artifactId>agentic-spring-ai-admin-server-core</artifactId>
            <version>${project.parent.version}</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
    </dependencies>
</project>
